<h2>Add details</h2>

<?php echo $this->tag->form("test/index"); ?>

<table>
        <tr><td>
        <label for="name">Name</label>
        </td><td>
        <?php echo $this->tag->textField("name"); ?>
        </td></tr>

        <tr><td>
        <label for="email">E-Mail</label>
        </td><td>
        <?php echo $this->tag->emailField("email"); ?>
        </td></tr>

        <tr><td>
        <label for="profession">Profession</label>
        </td><td>
        <?php echo $this->tag->textField("profession"); ?>
        </td></tr>
        </table>
    <p>
        <?php echo $this->tag->submitButton("Add User"); ?>
    </p>

</form>

<br/>
<?php
echo $this->tag->linkTo(
    '/test/show',
    'see all users!'
);
