<h4>All Users</h4>
<table class="table table-bordered table-hover">
    <thead class="thead-light">
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Profession</th>
            <th>Action</th>
            <th>Edit</th>
        </tr>
    </thead>
    <tbody>
    <?php
    foreach ($result as $key => $value) {
        echo '<tr>
            <td>' . $value->name . '</td>
            <td>' . $value->email. '</td>
            <td>' . $value->profession. '</td>
            <td><a href="/test/delete/'.$value->_id.'">delete</a></td>
            <td><a href="/test/update/'.$value->_id.'">edit</a></td>
        </tr>';
    }?>
    </tbody>
</table>
<br/>
<br/>
<?php
echo $this->tag->linkTo(
    '/test/add',
    'add more!'
);